name: continuous-integration
run-name: Build and Test

on: [push]

jobs:
  build-debug:
    name: build-debug
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
      GENERATOR: Ninja
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Setup OpenCV
        uses: Dovyski/setup-opencv-action@v1.1
        with:
          opencv-version: '4.7.0'
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -G ${{env.GENERATOR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake -B ${{github.workspace}}/build -t seam_carving
