name: pushok
on: [push]

jobs:
  lib-debug:
    name: lib-debug / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@main
      - name: Run CMake with Ninja and vcpkg
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: debug
          buildPreset: unit-test
          testPreset: unit

#  lib-release:
#    name: lib-release / ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [macos-latest]
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#          fetch-depth: 0
#      - uses: lukka/get-cmake@latest
#      - uses: lukka/run-vcpkg@main
#      - name: Run CMake with Ninja and vcpkg
#        uses: lukka/run-cmake@v10
#        with:
#          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
#          configurePreset: release
#          buildPreset: lib-release

  unit-test:
    name: unit-test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@main
      - name: Run CMake with Ninja and vcpkg
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: debug
          buildPreset: unit-test
          testPreset: unit
