name: pushok
on: [push]

jobs:
  lib-debug:
    name: lib-debug / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
#      - uses: hendrikmuhs/ccache-action@v1.2
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@main
      - name: Run CMake with Ninja and vcpkg
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: default
#          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
          buildPreset: lib-debug
  unit-test:
    name: unit-test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: lib-debug
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@main
      - name: Run CMake with Ninja and vcpkg
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: default
#          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"
          buildPreset: unit-test
          testPreset: unit
