name: pushok
on: [push]

jobs:
#  lib-debug:
#    name: lib-debug / ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [macos-latest]
#    env:
#      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#          fetch-depth: 0
#      - uses: lukka/get-cmake@latest
#      - uses: lukka/run-vcpkg@main
#      - name: Run CMake with Ninja and vcpkg
#        uses: lukka/run-cmake@v10
#        with:
#          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
#          configurePreset: default
#          buildPreset: lib-debug
  unit-test:
    name: unit-test / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
#    needs: lib-debug
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-osx
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'
          runVcpkgInstall: false
      - name: Run CMake with Ninja and vcpkg
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: default
          buildPreset: unit-test
          testPreset: unit
